【2022-03-07 10:03:30,848-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:11:59,570-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:12:34,104-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:15:55,213-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:16:41,925-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:18:06,742-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:18:38,227-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:20:39,725-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:20:56,449-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:22:48,067-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:27:31,089-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:27:58,360-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:28:09,760-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:31:48,769-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:40:02,188-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 10:44:28,025-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:06:39,426-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:07:50,193-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:09:31,493-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:10:51,999-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:11:36,965-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:14:25,468-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:15:01,107-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:15:43,533-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:18:44,461-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:28:58,466-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:32:09,996-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:32:24,235-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:41:07,430-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:42:04,531-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:42:18,099-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:45:13,996-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:46:56,617-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:47:06,308-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 11:48:36,834-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 12:08:47,630-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 12:10:33,249-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 12:12:27,118-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 12:15:47,529-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 12:19:58,896-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 12:20:05,738-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 12:20:33,011-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:05:46,853-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:07:26,560-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:09:55,703-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:12:00,453-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:13:06,269-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:20:19,250-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:20:36,143-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:24:46,536-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:26:03,823-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:26:28,465-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 15:27:57,392-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:21:17,890-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:21:27,370-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:22:02,663-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:23:13,952-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:25:04,752-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:28:18,174-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:30:15,618-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:32:50,550-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:34:17,092-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:34:19,103-test_log-ERROR-test_all.py-test_all-[line:83】：list indices must be integers or slices, not str
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
TypeError: list indices must be integers or slices, not str
【2022-03-07 17:35:07,913-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:35:31,912-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:36:08,909-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:36:11,097-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,413-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,428-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,438-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,452-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,481-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,494-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,509-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,519-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,528-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,539-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,568-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,590-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,605-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,637-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,652-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,661-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:36:11,672-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:50:33,032-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:50:51,782-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:50:54,130-test_log-ERROR-test_all.py-test_all-[line:83】：list indices must be integers or slices, not str
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
TypeError: list indices must be integers or slices, not str
【2022-03-07 17:51:15,568-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 17:51:17,641-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,127-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,150-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,167-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,178-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,187-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,196-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,225-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,233-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,259-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,278-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,287-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,298-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,332-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,347-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,359-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,390-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 17:51:18,402-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:12,972-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 18:03:15,067-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,084-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,085-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,092-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,101-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,103-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,104-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,105-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,106-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,106-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,107-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,108-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,109-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,109-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,110-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,115-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,124-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:03:15,131-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:21,026-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 18:06:22,991-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:22,993-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:22,994-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:22,995-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,009-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,016-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,020-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,023-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,026-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,028-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,030-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,032-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,034-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,035-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,036-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,036-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,037-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:06:23,039-test_log-ERROR-test_all.py-test_all-[line:83】：'set_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 41, in test_all
    if case["set_sql"]:
KeyError: 'set_sql'
【2022-03-07 18:09:36,843-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 18:10:17,219-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 18:23:16,589-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 18:23:18,533-test_log-ERROR-test_all.py-test_all-[line:83】：invalid syntax (<unknown>, line 1)
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 42, in test_all
    for sql in ast.literal_eval(case["setup_sql"]):
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    select * from shang_join_information
             ^
SyntaxError: invalid syntax
【2022-03-07 18:23:19,011-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,023-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,034-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,044-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,054-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,065-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,074-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,084-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,095-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,123-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,139-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,191-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,207-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,224-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,277-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,298-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:19,308-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:49,130-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 18:23:55,839-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 18:23:58,119-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,130-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,131-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,132-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,133-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,133-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,134-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,135-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,136-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,142-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,152-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,153-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,154-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,155-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,156-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,157-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,158-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:23:58,159-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:16,857-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 18:24:18,935-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,221-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,258-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,278-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,290-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,305-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,316-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,351-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,372-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,386-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,413-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,427-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,437-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,448-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,456-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,484-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,493-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 18:24:19,504-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:30,530-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 19:23:32,654-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,670-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,671-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,672-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,673-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,674-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,675-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,675-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,676-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,677-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,678-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,682-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,691-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,696-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,705-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,713-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,718-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:23:32,722-test_log-ERROR-test_all.py-test_all-[line:83】：'TestAll' object has no attribute 'replace'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.replace.replace_data(data=case["data"],sql=case["replace_sql"])
AttributeError: 'TestAll' object has no attribute 'replace'
【2022-03-07 19:24:59,708-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 19:25:01,841-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,856-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,857-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,858-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,858-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,871-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,876-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,877-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,878-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,879-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,880-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,881-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,882-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,883-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,884-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,884-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,885-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:25:01,886-test_log-ERROR-test_all.py-test_all-[line:83】：'replace_sql'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
KeyError: 'replace_sql'
【2022-03-07 19:33:02,956-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 19:33:04,734-test_log-ERROR-test_all.py-test_all-[line:83】：malformed node or string: <ast.Name object at 0x000002194A7C7BE0>
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
  File "D:\workspace\PycharmProjects\Api_Feng\test_tools\handle_replace.py", line 75, in replace_data
    return ast.literal_eval(data)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 94, in _convert
    return dict(zip(map(_convert, node.keys),
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 94, in _convert
    return dict(zip(map(_convert, node.keys),
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <ast.Name object at 0x000002194A7C7BE0>
【2022-03-07 19:33:05,287-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,307-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,316-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,340-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,350-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,375-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,386-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,397-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,423-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,452-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,464-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,490-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,500-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,542-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,556-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,566-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:05,576-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:15,147-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 19:33:18,914-test_log-ERROR-test_all.py-test_all-[line:83】：malformed node or string: <ast.Name object at 0x0000020DB7910B50>
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
  File "D:\workspace\PycharmProjects\Api_Feng\test_tools\handle_replace.py", line 75, in replace_data
    return ast.literal_eval(data)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 94, in _convert
    return dict(zip(map(_convert, node.keys),
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 94, in _convert
    return dict(zip(map(_convert, node.keys),
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <ast.Name object at 0x0000020DB7910B50>
【2022-03-07 19:33:18,927-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,928-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,929-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,929-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,930-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,932-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,932-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,933-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,934-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,935-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,935-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,936-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,939-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,949-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,952-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,953-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:33:18,954-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:43,996-test_log-INFO-handle_log.py-<module>-[line:36】：test
【2022-03-07 19:49:46,192-test_log-ERROR-test_all.py-test_all-[line:83】：malformed node or string: <ast.Name object at 0x00000209E14C1B50>
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 48, in test_all
    new_data = self.hanlde_replace.replace_data(data=case["data"],sql=case["replace_sql"])
  File "D:\workspace\PycharmProjects\Api_Feng\test_tools\handle_replace.py", line 75, in replace_data
    return ast.literal_eval(data)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 94, in _convert
    return dict(zip(map(_convert, node.keys),
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 94, in _convert
    return dict(zip(map(_convert, node.keys),
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "C:\Programsoft\Python\Python39\lib\ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <ast.Name object at 0x00000209E14C1B50>
【2022-03-07 19:49:46,225-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,228-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,232-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,235-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,237-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,238-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,241-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,244-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,245-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,246-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,247-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,249-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,250-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,252-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,254-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,255-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
【2022-03-07 19:49:46,257-test_log-ERROR-test_all.py-test_all-[line:83】：'check_dy_dynamic'
Traceback (most recent call last):
  File "D:\workspace\PycharmProjects\Api_Feng\test_case\test_all.py", line 52, in test_all
    if str(case["check_dy_dynamic"]) == "1":
KeyError: 'check_dy_dynamic'
